(function(g){var window=this;var aBa=function(a,b){return g.Wb(a,b)},n6=function(a){g.Om(a,"zx",g.yb());
return a},o6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Rm(a.g,b,c)},bBa=function(a,b){var c=[];
g.uk(b,function(a){try{var b=g.jD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.iD(b)&&c.push(a):c.push(a)},a);
return c},cBa=function(a,b){var c=bBa(a,b);
(0,g.B)(c,function(a){g.jD.prototype.remove.call(this,a)},a)},dBa=function(a,b,c,d){var e=new g.Fm(null,void 0);
a&&g.Gm(e,a);b&&g.Hm(e,b);c&&g.Im(e,c);d&&g.Jm(e,d);return e},eBa=function(a){g.eG[a]&&(a=g.eG[a],(0,g.B)(a,function(a){g.cG[a]&&delete g.cG[a]}),a.length=0)},fBa=function(a){var b=g.bG();
if(b)if(b.clear(a),a)eBa(a);else for(var c in g.eG)eBa(c)},p6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.zm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gBa(this,a.capabilities||""),hBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},gBa=function(a,b){a.capabilities.clear();
(0,g.Ld)(b.split(","),g.Fa(aBa,iBa)).forEach(function(b){a.capabilities.add(b)})},hBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},q6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},r6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kBa=function(a){return new q6(a)},lBa=function(a){return g.za(a)?(0,g.G)(a,kBa):[]},s6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},t6=function(a){return g.za(a)?"["+(0,g.G)(a,s6).join(",")+"]":"null"},u6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},mBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},v6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},w6=function(a,b){return g.Ma(a,function(a){return r6(a,b)})},nBa=function(){var a=(0,g.YG)();
a&&cBa(a,a.g.Md(!0))},x6=function(){var a=g.aH("yt-remote-connected-devices")||[];
g.jb(a);return a},oBa=function(a){if(g.Ra(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},pBa=function(a){g.$G("yt-remote-connected-devices",a,86400)},z6=function(){if(y6)return y6;
var a=g.aH("yt-remote-device-id");a||(a=u6(),g.$G("yt-remote-device-id",a,31536E3));for(var b=x6(),c=1,d=a;g.Qa(b,d);)c++,d=a+"#"+c;return y6=d},A6=function(){var a=x6(),b=z6();
g.Qa(a,b);g.cH()&&g.lb(a,b);a=oBa(a);if(g.Ra(a))try{g.LG("remote_sid")}catch(c){}else try{g.KG("remote_sid",a.join(","),-1)}catch(c){}},qBa=function(){return g.aH("yt-remote-session-browser-channel")},rBa=function(){return g.aH("yt-remote-local-screens")||[]},sBa=function(){g.$G("yt-remote-lounge-token-expiration",!0,86400)},tBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(rBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.om)(c,function(a){return!g.Qa(b,a)})&&sBa();
g.$G("yt-remote-local-screens",a,31536E3)},uBa=function(a,b){g.$G("yt-remote-session-browser-channel",a);
g.$G("yt-remote-session-screen-id",b);var c=x6(),d=z6();g.Qa(c,d)||c.push(d);pBa(c);A6()},B6=function(a){a||(g.bH("yt-remote-session-screen-id"),g.bH("yt-remote-session-video-id"));
A6();a=x6();g.Va(a,z6());pBa(a)},vBa=function(){if(!C6){var a=g.uD();
a&&(C6=new g.dD(a))}return C6?!!C6.get("yt-remote-use-staging-server"):!1},wBa=function(){var a=window.document.createElement("a");
g.$c(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},xBa=function(a,b){var c=g.Ed("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.de("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},yBa=function(){var a=wBa(),b=window.document.getElementById(a),c=b&&g.oF(b,"loaded");
c||b&&!c||(b=xBa(a,function(){g.oF(b,"loaded")||(g.nF(b,"loaded","true"),g.iG(a),g.cE(g.Fa(fBa,a),0))}))},D6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},zBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},E6=function(a){a.length?ABa(a.shift(),function(){E6(a)}):F6()},BBa=function(a){return"chrome-extension://"+a+G6},ABa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},H6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},F6=function(){var a=zBa();
a&&a(!1,"No cast extension found")},I6=function(){if(CBa){var a=2,b=zBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ABa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",F6,c)}},DBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(I6(),a({command:"cast.sender.init"}))},EBa=function(){I6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);E6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+G6,"//www.gstatic.com/eureka/clank"+G6])},J6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.dd=b;this.B=(0,g.z)(this.II,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},K6=function(){},L6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Vm(this);this.l=new g.ug;this.l.setInterval(250)},GBa=function(a,b,c){a.vj=1;
a.eh=n6(b.clone());a.Ei=c;a.C=!0;FBa(a,null)},M6=function(a,b,c,d,e){a.vj=1;
a.eh=n6(b.clone());a.Ei=null;a.C=c;e&&(a.cD=!1);FBa(a,d)},FBa=function(a,b){a.bk=(0,g.F)();
N6(a);a.zh=a.eh.clone();o6(a.zh,"t",a.D);a.Zl=0;a.Pc=a.g.Hq(a.g.Tl()?b:null);0<a.qr&&(a.Oo=new g.Yk((0,g.z)(a.pE,a,a.Pc),a.qr));a.A.T(a.Pc,"readystatechange",a.XT);var c=a.fi?g.dc(a.fi):{};a.Ei?(a.Cp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Pc.send(a.zh,a.Cp,a.Ei,c)):(a.Cp="GET",a.cD&&!g.Ad&&(c.Connection="close"),a.Pc.send(a.zh,a.Cp,null,c));a.g.nf(1)},JBa=function(a,b,c){for(var d=!0;!a.Ph&&a.Zl<c.length;){var e=HBa(a,c);
if(e==O6){4==b&&(a.fh=4,P6(15),d=!1);break}else if(e==IBa){a.fh=4;P6(16);d=!1;break}else Q6(a,e)}4==b&&0==c.length&&(a.fh=1,P6(17),d=!1);a.uf=a.uf&&d;d||(R6(a),S6(a))},HBa=function(a,b){var c=a.Zl,d=b.indexOf("\n",c);
if(-1==d)return O6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return IBa;d+=1;if(d+c>b.length)return O6;var e=b.substr(d,c);a.Zl=d+c;return e},LBa=function(a,b){a.bk=(0,g.F)();
N6(a);var c=b?window.location.hostname:"";a.zh=a.eh.clone();g.Om(a.zh,"DOMAIN",c);g.Om(a.zh,"t",a.D);try{a.vf=new window.ActiveXObject("htmlfile")}catch(n){R6(a);a.fh=7;P6(22);S6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in T6)k=T6[l];else if(l in KBa)k=T6[l]=KBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=T6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.xc("b/12014412"),d);a.vf.open();a.vf.write(g.Uc(c));a.vf.close();a.vf.parentWindow.m=(0,g.z)(a.cT,a);a.vf.parentWindow.d=(0,g.z)(a.oC,a,!0);a.vf.parentWindow.rpcClose=(0,g.z)(a.oC,a,!1);c=a.vf.createElement("DIV");a.vf.parentWindow.document.body.appendChild(c);d=g.Kc(a.zh.toString());d=g.sb(g.Hc(d));d=g.bd(g.xc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Uc(d);
a.g.nf(1)},N6=function(a){a.cv=(0,g.F)()+a.B;
MBa(a,a.B)},MBa=function(a,b){if(null!=a.uk)throw Error("WatchDog timer not null");
a.uk=U6((0,g.z)(a.sT,a),b)},V6=function(a){a.uk&&(g.w.clearTimeout(a.uk),a.uk=null)},S6=function(a){a.g.uy()||a.Ph||a.g.Co(a)},R6=function(a){V6(a);
g.cf(a.Oo);a.Oo=null;a.l.stop();g.an(a.A);if(a.Pc){var b=a.Pc;a.Pc=null;b.abort();b.dispose()}a.vf&&(a.vf=null)},Q6=function(a,b){try{a.g.hC(a,b),a.g.nf(4)}catch(c){}},OBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;NBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){OBa(a,b,c,d,f)},f)})}},NBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{W6(d),c(!0)}catch(e){}};
d.onerror=function(){try{W6(d),c(!1)}catch(e){}};
d.onabort=function(){try{W6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{W6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},W6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},PBa=function(a){this.g=a;
this.l=new K6},QBa=function(a){var b=X6(a.g,a.zk,"/mail/images/cleardot.gif");
n6(b);OBa(b.toString(),5E3,(0,g.z)(a.VH,a),3,2E3);a.nf(1)},Z6=function(a){var b=a.g.H;
if(null!=b)P6(5),b?(P6(11),Y6(a.g,a,!1)):(P6(12),Y6(a.g,a,!0));else if(a.te=new L6(a,void 0,void 0,void 0),a.te.fi=a.lr,b=a.g,b=X6(b,b.Tl()?a.Xk:null,a.pr),P6(5),!g.yd||g.tc(10))o6(b,"TYPE","xmlhttp"),M6(a.te,b,!1,a.Xk,!1);else{o6(b,"TYPE","html");var c=a.te;a=!!a.Xk;c.vj=3;c.eh=n6(b.clone());LBa(c,a)}},$6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new K6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},RBa=function(a,b){this.g=a;
this.map=b;this.context=null},SBa=function(a){g.ef.call(this,"statevent",a)},TBa=function(a,b){g.ef.call(this,"timingevent",a);
this.size=b},UBa=function(a){g.ef.call(this,"serverreachability",a)},XBa=function(a){VBa(a);
if(3==a.g){var b=a.Fl++,c=a.An.clone();g.Om(c,"SID",a.o);g.Om(c,"RID",b);g.Om(c,"TYPE","terminate");a7(a,c);b=new L6(a,a.o,b,void 0);b.vj=2;b.eh=n6(c.clone());(new window.Image).src=b.eh;b.bk=(0,g.F)();N6(b)}WBa(a)},YBa=function(a){a.pI(1,0);
a.An=X6(a,null,a.kr);b7(a)},VBa=function(a){a.Tg&&(a.Tg.abort(),a.Tg=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.kg&&(g.w.clearTimeout(a.kg),a.kg=null);c7(a);a.Rd&&(a.Rd.cancel(),a.Rd=null);a.Vg&&(g.w.clearTimeout(a.Vg),a.Vg=null)},ZBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new RBa(a.RO++,b));2!=a.g&&3!=a.g||b7(a)},b7=function(a){a.Rd||a.Vg||(a.Vg=U6((0,g.z)(a.mC,a),0),a.jj=0)},aCa=function(a,b){if(1==a.g){if(!b){a.Fl=Math.floor(1E5*Math.random());
var c=a.Fl++,d=new L6(a,"",c,void 0);d.fi=null;var e=d7(a),f=a.An.clone();g.Om(f,"RID",c);g.Om(f,"CVER","1");a7(a,f);GBa(d,f,e);a.Rd=d;a.g=2}}else 3==a.g&&(b?$Ba(a,b):0==a.l.length||a.Rd||$Ba(a))},$Ba=function(a,b){if(b)if(6<a.Rh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Fl-1;var d=d7(a)}else c=b.F,d=b.Ei;else c=a.Fl++,d=d7(a);var e=a.An.clone();g.Om(e,"SID",a.o);g.Om(e,"RID",c);g.Om(e,"AID",a.Jj);a7(a,e);c=new L6(a,a.o,c,a.jj+1);c.fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Rd=c;GBa(c,e,d)},a7=function(a,b){if(a.qd){var c=a.qd.Xx();
c&&g.Lb(c,function(a,c){g.Om(b,c,a)})}},d7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Rh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Rh?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},bCa=function(a){a.wc||a.kg||(a.D=1,a.kg=U6((0,g.z)(a.lC,a),0),a.Wi=0)},e7=function(a){if(a.wc||a.kg||3<=a.Wi)return!1;
a.D++;a.kg=U6((0,g.z)(a.lC,a),cCa(a,a.Wi));a.Wi++;return!0},Y6=function(a,b,c){a.Ap=c;
a.If=b.sg;a.C||YBa(a)},c7=function(a){null!=a.Th&&(g.w.clearTimeout(a.Th),a.Th=null)},cCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},f7=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.PU,a);c||(c=new g.Fm("//www.google.com/images/cleardot.gif"),n6(c));NBa(c.toString(),1E4,d)}else P6(2);dCa(a,b)},dCa=function(a,b){a.g=0;
a.qd&&a.qd.Rw(b);WBa(a);VBa(a)},WBa=function(a){a.g=0;
a.If=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.uq();else{g.Za(a.A);var b=g.Za(a.l);a.A.length=0;a.l.length=0;a.qd.uq(b)}},X6=function(a,b,c){var d=g.Pm(c);
if(""!=d.l)b&&g.Hm(d,b+"."+d.l),g.Im(d,d.B);else{var e=window.location;d=dBa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Kk&&g.Lb(a.Kk,function(a,b){g.Om(d,b,a)});
g.Om(d,"VER",a.Rh);a7(a,d);return d},U6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},P6=function(a){g7.dispatchEvent(new SBa(g7,a))},eCa=function(){},fCa=function(a,b){this.action=a;
this.params=b||{}},h7=function(a,b){g.K.call(this);
this.g=new g.fu(this.SS,0,this);g.L(this,this.g);this.dd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},i7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.cD;this.l=new h7(this.yV,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},gCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ap,sessionId:a.g.o,arrayId:a.g.Jj}},hCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&aCa(a.g),XBa(a.g));a.F=0},j7=function(a){return!!a.g&&3==a.g.g},iCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},k7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Lg(a)||"";b&&(this.port=":"+b);this.domain=g.Kg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.l=!1))},l7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Ug(c+b,{})},m7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),wd:g.Fa(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.AE(b,a)},mCa=function(){var a=jCa;
kCa();n7.push(a);lCa(n7)},o7=function(a,b){kCa();
var c=n7,d=nCa(a,String(b));g.Ra(c)?oCa(d):(lCa(c),(0,g.B)(c,function(a){a(d)}))},kCa=function(){n7||(n7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",n7,void 0))},oCa=function(a){var b=(p7+1)%50;
p7=b;q7[b]=a;r7||(r7=49==b)},lCa=function(a){var b=q7;
if(b[0]){var c=p7,d=r7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
q7=Array(50);p7=-1;r7=!1}},nCa=function(a,b){var c=((0,g.F)()-pCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},s7=function(a){g.UF.call(this);
this.D=a;this.g=[]},qCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},rCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Ld)(a.g,function(a){return!!v6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=qCa(a,b[d])||c;return c},sCa=function(a,b){var c=a.g.length;
a.g=(0,g.Ld)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},t7=function(a,b,c,d){g.UF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},v7=function(a){s7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;u7(this);this.info("Initializing with "+t6(this.g))},tCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=l7(a.o,"/pairing/get_lounge_token_batch");
m7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.XI,a),(0,g.z)(a.WI,a))}},u7=function(a){var b=lBa(rBa());
b=(0,g.Ld)(b,function(a){return!a.uuid});
return rCa(a,b)},w7=function(a,b){tBa((0,g.G)(a.g,jBa));
b&&sBa()},y7=function(a,b){g.UF.call(this);
this.C=b;var c=g.aH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Qa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;x7("Initialized with "+g.Bg(this.g))},uCa=function(a,b,c){var d=l7(a.B,"/pairing/get_screen_availability");
m7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},z7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(x7("Updated online screens: "+g.Bg(a.g)),a.g=b,a.R("screenChange"));vCa(a)},A7=function(a){(0,window.isNaN)(a.o)||g.eE(a.o);
a.o=g.cE((0,g.z)(a.nu,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},x7=function(a){o7("OnlineScreenService",a)},wCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},vCa=function(a){a=g.Tb(g.Nb(a.g,function(a){return a}));
g.jb(a);a.length?g.$G("yt-remote-online-screen-ids",a.join(","),60):g.bH("yt-remote-online-screen-ids")},B7=function(a){s7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};xCa(this)},zCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?w6(k,c):null)||w6(k,b)){k.uuid=b;var l=C7(a,k);uCa(a.l,l,function(a){e(a?l:null)})}else c?yCa(a,c,(0,g.z)(function(a){var f=C7(this,new q6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));uCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},ACa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},yCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.AE(l7(a.C,"/pairing/get_lounge_token_batch"),e)},BCa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+t6(a.g))},xCa=function(a){D7(a);
a.o=new v7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.mJ,a));BCa(a);a.A=lBa(g.aH("yt-remote-automatic-screen-cache")||[]);D7(a);a.info("Initializing automatic screens: "+t6(a.A));a.l=new y7(a.C,(0,g.z)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},C7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=w6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.$G("yt-remote-automatic-screen-cache",(0,g.G)(a.A,jBa)));D7(a);a.B[b.uuid]=b.id;g.$G("yt-remote-device-id-map",a.B,31536E3);return b},D7=function(a){a.B=g.aH("yt-remote-device-id-map")||{}},E7=function(a,b,c){g.UF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},F7=function(a,b){o7(a.M,b)},G7=function(a,b){E7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.FV,this);this.B=(0,g.z)(this.ET,this);this.A=g.cE((0,g.z)(function(){CCa(this,null)},this),12E4)},DCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){F7(this,"Failed to send message: getMdxSessionStatus.")},a)):F7(a,"Sending yt message without session: "+g.Bg(b))},CCa=function(a,b){g.eE(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Do,a),d=(0,g.z)(a.se,a);a.ky(b,c,d,5)}}else a.se(Error("Waiting for session status timed out."))},H7=function(a,b,c){E7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.IV,this);this.g=g.y},ECa=function(a){a.g=a.H.wE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Do(a)},a),(0,g.z)(function(a){this.g=g.y;
this.se(a)},a))},FCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}vBa()&&(b.env_useStageMdx=1);return g.Sg(b)},I7=function(a,b){E7.call(this,a,b,"ManualSession");
this.g=g.cE((0,g.z)(this.Kj,this,null),150)},J7=function(a,b,c,d){g.UF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.gS,this)},GCa=function(a,b){return b?g.Ma(a.o,function(a){return r6(b,a.label)},a):null},K7=function(a){o7("Controller",a)},jCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},L7=function(a){return a.B||!!a.o.length||!!a.g},M7=function(a,b,c){b!=a.g&&(g.cf(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.jC,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Kj(null)):a.R("yt-remote-cast2-session-change",null))},HCa=function(a){var b=a.l.vE(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&r6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=GCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},NCa=function(a,b,c,d,e,f,k){ICa()?JCa(b,e,f,k)&&(O7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?KCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?KCa(a,c):(P7("Failed to load cast API: "+d),Q7(!1),O7(!1),g.bH("yt-remote-cast-available"),g.bH("yt-remote-cast-receiver"),LCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):yBa():H6("CriOS")?DBa():H6("Android")&&H6("Chrome/")&&window.navigator.presentation?EBa():window.chrome&&window.navigator.presentation&&!H6("Edge")?(I6(),E6(MCa.map(BBa))):F6())):N7("Cannot initialize because not running Chrome")},LCa=function(){N7("dispose");
var a=R7();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);OCa(!1);g.gG(S7);S7.length=0},T7=function(){return!!g.aH("yt-remote-cast-installed")},PCa=function(){var a=g.aH("yt-remote-cast-receiver");
return a?a.friendlyName:null},QCa=function(){N7("clearCurrentReceiver");
g.bH("yt-remote-cast-receiver")},RCa=function(){return T7()?R7()?R7().getCastSession():(P7("getCastSelector: Cast is not initialized."),null):(P7("getCastSelector: Cast API is not installed!"),null)},V7=function(){T7()?R7()?U7()?(N7("Requesting cast selector."),R7().requestSession()):(N7("Wait for cast API to be ready to request the session."),S7.push(g.fG("yt-remote-cast2-api-ready",V7))):P7("requestCastSelector: Cast is not initialized."):P7("requestCastSelector: Cast API is not installed!")},W7=
function(a,b){U7()?R7().setConnectedScreenStatus(a,b):P7("setConnectedScreenStatus called before ready.")},ICa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.LH||a},SCa=function(a,b){R7().init(a,b)},JCa=function(a,b,c,d){var e=!1;
R7()||(a=new J7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.$G("yt-remote-cast-available",a);g.jG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){N7("onReceiverSelected: "+a.friendlyName);
g.$G("yt-remote-cast-receiver",a);g.jG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){N7("onReceiverResumed: "+a.friendlyName);
g.$G("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){N7("onSessionChange: "+s6(a));
a||g.bH("yt-remote-cast-receiver");g.jG("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
N7("cloudview.createSingleton_: "+e);return e},R7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},KCa=function(a,b){Q7(!0);
O7(!1);SCa(a,function(a){a?(OCa(!0),g.iG("yt-remote-cast2-api-ready")):(P7("Failed to initialize cast API."),Q7(!1),g.bH("yt-remote-cast-available"),g.bH("yt-remote-cast-receiver"),LCa());b(a)})},N7=function(a){o7("cloudview",a)},P7=function(a){o7("cloudview",a)},Q7=function(a){N7("setCastInstalled_ "+a);
g.$G("yt-remote-cast-installed",a)},U7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},OCa=function(a){N7("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},O7=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},X7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Lf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},Y7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},Z7=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},$7=function(a,b){a.F=b;
a.D=(0,g.F)()},a8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},b8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&Y7(a)},c8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.l);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},e8=function(a,b){g.UF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.tC;this.o=this.l=null;this.H=(0,g.z)(this.BP,this);this.D=(0,g.z)(this.Il,this);this.F=(0,g.z)(this.AP,this);this.I=(0,g.z)(this.OP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.jv,this),TCa(this))):c=3;0!=c&&(b?this.jv(c):g.cE((0,g.z)(function(){this.jv(c)},this),0));
var d=RCa();d&&d8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},f8=function(a){return new X7(a.A.getPlayerContextData())},TCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.bS,a),this))},a)},UCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},g8=function(a,b){50>a.B.Ec()&&g.vC(a.B,b)},i8=function(a,b,c){var d=f8(a);
$7(d,c);-1E3!=d.g&&(d.g=b);h8(a,d)},j8=function(a,b,c){a.A.sendMessage(b,c)},h8=function(a,b){UCa(a);
a.A.setPlayerContextData(c8(b));TCa(a)},d8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Il(null));
a.o=b;a.o&&(o7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Il(a.o.media[0]))},VCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=f8(a);b.contentId!=d.videoId&&o7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;$7(d,a.l.getEstimatedTime());h8(a,d)}else o7("CP","No cast media video. Ignoring state update.")},k8=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),j8(this,b,c))},a)},l8=function(a,b,c){g.UF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.P=[];this.A=this.D=this.o=this.Za=this.g=null;this.pa=a;this.P.push(g.EF(window,"beforeunload",(0,g.z)(this.MI,this)));this.l=[];this.Za=new X7;this.X=b.id;this.g=WCa(this,c);this.g.subscribe("handlerOpened",this.FP,this);this.g.subscribe("handlerClosed",this.CP,this);this.g.subscribe("handlerError",this.DP,this);this.g.subscribe("handlerMessage",this.EP,this);iCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.cH()&&g.$G("yt-remote-session-video-id",a)},this)},m8=function(a){o7("conn",a)},WCa=function(a,b){return new i7(l7(a.pa,"/bc"),b)},n8=function(a,b){a.R("proxyStateChange",b)},XCa=function(a){a.B=g.cE((0,g.z)(function(){m8("Connecting timeout");
this.C(1)},a),2E4)},o8=function(a){g.eE(a.B);
a.B=window.NaN},p8=function(a){g.eE(a.M);
a.M=window.NaN},YCa=function(a){q8(a);
a.K=g.cE((0,g.z)(function(){r8(this,"getNowPlaying")},a),2E4)},q8=function(a){g.eE(a.K);
a.K=window.NaN},$Ca=function(a,b){b&&(o8(a),p8(a));
b==(j7(a.g)&&(0,window.isNaN)(a.B))?b&&(n8(a,1),r8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),n8(a,1),r8(a,"getNowPlaying"),ZCa(a)):a.C(1)},aDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Zb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},bDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;b8(a.Za,c,d);a.R("remoteQueueChange")},dDa=function(a,b){b.params=b.params||{};
bDa(a,b);cDa(a,b);a.R("autoplayDismissed")},cDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
$7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?YCa(a):q8(a);
a.R("remotePlayerChange")},eDa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);$7(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},fDa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},gDa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},hDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Lf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},ZCa=function(a){g.eE(a.I);
a.I=g.cE((0,g.z)(a.C,a,1),864E5)},r8=function(a,b,c){c?m8("Sending: action="+b+", params="+g.Bg(c)):m8("Sending: action="+b);
a.g.sendMessage(b,c)},s8=function(a){s7.call(this,"ScreenServiceProxy");
this.cd=a;this.l=[];this.l.push(this.cd.$_s("screenChange",(0,g.z)(this.CV,this)));this.l.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.CR,this)))},mDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.XD("MDX_CONFIG")||b;nBa();A6();t8||(t8=new k7(b?b.loungeApiHost:void 0),vBa()&&(t8.g="/api/loungedev"));u8||(u8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",u8,void 0));iDa();var c=v8();if(!c){var d=new B7(t8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=v8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);NCa(a,d,function(a){a?w8()&&W7(w8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.jG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),x8("Initializing: "+g.Bg(b)),y8.push(g.fG("yt-remote-cast2-availability-change",function(){g.jG("yt-remote-receiver-availability-change")})),y8.push(g.fG("yt-remote-cast2-receiver-selected",function(){z8(null);
g.jG("yt-remote-auto-connect","cast-selector-receiver")})),y8.push(g.fG("yt-remote-cast2-receiver-resumed",function(){g.jG("yt-remote-receiver-resumed","cast-selector-receiver")})),y8.push(g.fG("yt-remote-cast2-session-change",jDa)),y8.push(g.fG("yt-remote-connection-change",function(a){a?W7(w8(),"YouTube TV"):A8()||(W7(null,null),QCa())})),a=B8(),b.isAuto&&(a.id+="#dial"),g.$F("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),x8(" -- with channel params: "+
g.Bg(a)),kDa(a),c.start(),w8()||lDa())},oDa=function(){var a=nDa();
T7()&&g.aH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},nDa=function(){var a=v8().cd.$_gos();
var b=C8();b&&D8()&&(v6(a,b)||a.push(b));return mBa(a)},E8=function(){var a=pDa();
!a&&T7()&&PCa()&&(a={key:"cast-selector-receiver",name:PCa()});return a},pDa=function(){var a=nDa(),b=C8();
b||(b=A8());return g.Ma(a,function(a){return b&&r6(b,a.key)?!0:!1})},C8=function(){var a=w8();
if(!a)return null;var b=v8().ke();return w6(b,a)},jDa=function(a){x8("remote.onCastSessionChange_: "+s6(a));
if(a){var b=C8();b&&b.id==a.id?W7(b.id,"YouTube TV"):(b&&F8(),G8(a,1))}else D8()&&F8()},F8=function(){U7()?R7().stopSession():P7("stopSession called before API ready.");
var a=D8();a&&(a.disconnect(1),H8(null))},I8=function(){var a=D8();
return!!a&&3!=a.getProxyState()},x8=function(a){o7("remote",a)},v8=function(){if(!J8){var a=g.x("yt.mdx.remote.screenService_");
J8=a?new s8(a):null}return J8},w8=function(){return g.x("yt.mdx.remote.currentScreenId_")},qDa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},rDa=function(){return g.x("yt.mdx.remote.connectData_")},z8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},D8=function(){return g.x("yt.mdx.remote.connection_")},H8=function(a){var b=D8();
z8(null);a||qDa("");g.wa("yt.mdx.remote.connection_",a,void 0);u8&&((0,g.B)(u8,function(b){b(a)}),u8.length=0);
b&&!a?g.jG("yt-remote-connection-change",!1):!b&&a&&g.jG("yt-remote-connection-change",!0)},A8=function(){var a=g.cH();
if(!a)return null;var b=v8().ke();return w6(b,a)},G8=function(a,b){C8()&&C8();
qDa(a.id);var c=new l8(t8,a,B8());c.connect(b,rDa());c.subscribe("beforeDisconnect",function(a){g.jG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){D8()&&H8(null)});
H8(c)},lDa=function(){var a=A8();
a?(x8("Resume connection to: "+s6(a)),G8(a,0)):(B6(),QCa(),x8("Skipping connecting because no session screen found."))},iDa=function(){var a=B8();
if(g.Zb(a)){a=z6();var b=g.aH("yt-remote-session-name")||"",c=g.aH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},B8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},kDa=function(a){a?(g.$G("yt-remote-session-app",a.app),g.$G("yt-remote-session-name",a.name)):(g.bH("yt-remote-session-app"),g.bH("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},K8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.RF(this);g.L(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.UQ);this.o.O(b,"captionschanged",this.zP);this.o.O(b,"captionssettingschanged",this.ID);this.o.O(b,"videoplayerreset",this.Eo);this.o.O(b,"mdxautoplaycancel",this.UH);this.P=this.o.O(b,"onVolumeChange",this.TB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.gC,this);c.subscribe("remotePlayerChange",this.Ll,this);c.subscribe("remoteQueueChange",this.Eo,this);c.subscribe("autoplayUpNext",this.DB,
this);c.subscribe("previousNextChange",this.dC,this);c.subscribe("nowAutoplaying",this.VB,this);c.subscribe("autoplayDismissed",this.CB,this);this.suggestion=null;this.H=new g.sP(64);this.A=new g.fu(this.ED,500,this);g.L(this,this.A);this.B=new g.fu(this.FD,1E3,this);g.L(this,this.B);this.K=new J6(this.fV,0,this);g.L(this,this.K);this.C={};this.M=new g.fu(this.gE,1E3,this);g.L(this,this.M);this.I=new g.Yk(this.EN,1E3,this);g.L(this,this.I);this.N=g.y;this.ID();this.Eo();this.Ll()},L8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},sDa=function(a){L8(a,0);
a.A.stop();M8(a,new g.sP(64))},O8=function(a,b){if(N8(a)&&!a.D){var c=null;
b&&(c={style:a.l.xi()},g.gc(c,b));a.g.vD(a.l.ea(1).videoId,c);a.C=f8(a.g).l}},P8=function(a,b){var c=a.l.Vf();
if(c){var d=c.he();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Fj;var m=f8(c);l=l||0;var n={videoId:k,currentIndex:l};b8(m,k,l);g.t(b)&&($7(m,b),n.currentTime=b);g.t(e)&&(n.listId=e);null!=d&&(n.playerParams=d);null!=f&&(n.clickTrackingParams=f);j8(c,"setPlaylist",n);e||h8(c,m);M8(a,new g.sP(1))},tDa=function(a,b){if(b){var c=a.l.zc("captions","tracklist",{gz:1});
c&&c.length?(a.l.Gd("captions","track",b),a.D=!1):(a.l.Nj("captions"),a.D=!0)}else a.l.Gd("captions","track",{})},N8=function(a){return f8(a.g).videoId==a.l.ea(1).videoId},M8=function(a,b){a.B.stop();
var c=a.H;if(!g.AP(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.XU(a.l,d);a.H=b;uDa(a.F,c,b)}},Q8=function(a){g.U.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.Ooa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.DV(this,250);g.L(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);vDa(this,g.UU(a))},vDa=function(a,b){if(3==a.o.Ua()){var c={RECEIVER_NAME:a.o.zc("remote","currentReceiver").name};
c=g.W(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.W(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},R8=function(a,b){g.OZ.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},S8=function(a){g.rV.call(this,a);
g.eH({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:u6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.sP(64);this.H=0;if(!g.JM(g.X(this.g))){a=
this.g;var b=g.YI(a);b&&(b=b.mo())&&(b=new R8(a,b),g.L(this,b));b=new Q8(a);g.L(this,b);g.lV(a,b.element,4)}},uDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.GP(c,b))},T8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)F8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Vf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Fj,index:Math.max(a.g.iA(),0),currentTime:0==f?void 0:f}}else c=null;x8("Connecting to: "+g.Bg(b));"cast-selector-receiver"==b.key?(z8(c||null),U7()?R7().setLaunchParams(c||null):P7("setLaunchParams called before ready.")):!c&&
I8()&&w8()==b.key?g.jG("yt-remote-connection-change",!0):(F8(),z8(c||null),c=v8().ke(),(c=w6(c,b.key))&&G8(c,1))}},KBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},T6={"'":"\\'"},wDa={},iBa={VW:"atp",o1:"ska",E0:"que",Q_:"mus",k1:"sus",eZ:"dsp"};
p6.prototype.gn=function(){var a=new p6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var C6,y6="",G6=D6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",CBa=D6("loadCastFramework")||D6("loadCastApplicationFramework"),MCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(J6,g.K);g.h=J6.prototype;g.h.HI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.F)()+this.dd:this.xa=g.vg(this.B,this.dd)};
g.h.stop=function(){this.xa&&(g.wg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();J6.Z.V.call(this)};
g.h.II=function(){this.o?(this.xa=g.vg(this.B,this.o-(0,g.F)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};K6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
K6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=L6.prototype;g.h.fi=null;g.h.uf=!1;g.h.uk=null;g.h.cv=null;g.h.bk=null;g.h.vj=null;g.h.eh=null;g.h.zh=null;g.h.Ei=null;g.h.Pc=null;g.h.Zl=0;g.h.vf=null;g.h.Cp=null;g.h.fh=null;g.h.Yk=-1;g.h.cD=!0;g.h.Ph=!1;g.h.qr=0;g.h.Oo=null;var IBa={},O6={};g.h=L6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.XT=function(a){a=a.target;var b=this.Oo;b&&3==g.tx(a)?b.tj():this.pE(a)};
g.h.pE=function(a){try{if(a==this.Pc)a:{var b=g.tx(this.Pc),c=this.Pc.l,d=this.Pc.getStatus();if(g.yd&&!g.tc(10)||g.Ad&&!g.sc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.gf&&!g.xx(this.Pc))break a;this.Ph||4!=b||7==c||(8==c||0>=d?this.g.nf(3):this.g.nf(2));V6(this);var e=this.Pc.getStatus();this.Yk=e;var f=g.xx(this.Pc);(this.uf=200==e)?(4==b&&R6(this),this.C?(JBa(this,b,f),g.gf&&this.uf&&3==b&&(this.A.T(this.l,"tick",this.ST),this.l.start())):Q6(this,f),this.uf&&!this.Ph&&(4==b?this.g.Co(this):
(this.uf=!1,N6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.fh=3,P6(13)):(this.fh=0,P6(14)),R6(this),S6(this))}}catch(k){this.Pc&&g.xx(this.Pc)}finally{}};
g.h.ST=function(){var a=g.tx(this.Pc),b=g.xx(this.Pc);this.Zl<b.length&&(V6(this),JBa(this,a,b),this.uf&&4!=a&&N6(this))};
g.h.cT=function(a){U6((0,g.z)(this.bT,this,a),0)};
g.h.bT=function(a){this.Ph||(V6(this),Q6(this,a),N6(this))};
g.h.oC=function(a){U6((0,g.z)(this.aT,this,a),0)};
g.h.aT=function(a){this.Ph||(R6(this),this.uf=a,this.g.Co(this),this.g.nf(4))};
g.h.cancel=function(){this.Ph=!0;R6(this)};
g.h.sT=function(){this.uk=null;var a=(0,g.F)();0<=a-this.cv?(2!=this.vj&&this.g.nf(3),R6(this),this.fh=2,P6(18),S6(this)):MBa(this,this.cv-a)};g.h=PBa.prototype;g.h.lr=null;g.h.te=null;g.h.Qo=!1;g.h.vy=null;g.h.wn=null;g.h.mr=null;g.h.pr=null;g.h.Me=null;g.h.sg=-1;g.h.Xk=null;g.h.zk=null;g.h.connect=function(a){this.pr=a;a=X6(this.g,null,this.pr);P6(3);this.vy=(0,g.F)();var b=this.g.F;null!=b?(this.Xk=b[0],(this.zk=b[1])?(this.Me=1,QBa(this)):(this.Me=2,Z6(this))):(o6(a,"MODE","init"),this.te=new L6(this,void 0,void 0,void 0),this.te.fi=this.lr,M6(this.te,a,!1,null,!0),this.Me=0)};
g.h.VH=function(a){if(a)this.Me=2,Z6(this);else{P6(4);var b=this.g;b.If=b.Tg.sg;f7(b,9)}a&&this.nf(2)};
g.h.Hq=function(a){return this.g.Hq(a)};
g.h.abort=function(){this.te&&(this.te.cancel(),this.te=null);this.sg=-1};
g.h.uy=function(){return!1};
g.h.hC=function(a,b){this.sg=a.Yk;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.If=this.sg;f7(c,2);return}this.Xk=c[0];this.zk=c[1]}else c=this.g,c.If=this.sg,f7(c,2);else if(2==this.Me)if(this.Qo)P6(7),this.mr=(0,g.F)();else if("11111"==b){if(P6(6),this.Qo=!0,this.wn=(0,g.F)(),c=this.wn-this.vy,!g.yd||g.tc(10)||500>c)this.sg=200,this.te.cancel(),P6(12),Y6(this.g,this,!0)}else P6(8),this.wn=this.mr=(0,g.F)(),this.Qo=!1};
g.h.Co=function(){this.sg=this.te.Yk;if(this.te.uf)0==this.Me?this.zk?(this.Me=1,QBa(this)):(this.Me=2,Z6(this)):2==this.Me&&((!g.yd||g.tc(10)?!this.Qo:200>this.mr-this.wn)?(P6(11),Y6(this.g,this,!1)):(P6(12),Y6(this.g,this,!0)));else{0==this.Me?P6(9):2==this.Me&&P6(10);var a=this.g;a.If=this.sg;f7(a,2)}};
g.h.Tl=function(){return this.g.Tl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.nf=function(a){this.g.nf(a)};g.h=$6.prototype;g.h.Kk=null;g.h.Rd=null;g.h.wc=null;g.h.kr=null;g.h.An=null;g.h.Iw=null;g.h.Ln=null;g.h.Fl=0;g.h.RO=0;g.h.qd=null;g.h.Vg=null;g.h.kg=null;g.h.Th=null;g.h.Tg=null;g.h.Ap=null;g.h.Jj=-1;g.h.wz=-1;g.h.If=-1;g.h.jj=0;g.h.Wi=0;g.h.Rh=8;var g7=new g.Gf;g.A(SBa,g.ef);g.A(TBa,g.ef);g.A(UBa,g.ef);g.h=$6.prototype;g.h.connect=function(a,b,c,d,e){P6(0);this.kr=b;this.Kk=c||{};d&&g.t(e)&&(this.Kk.OSID=d,this.Kk.OAID=e);this.C?(U6((0,g.z)(this.gx,this,a),100),YBa(this)):this.gx(a)};
g.h.gx=function(a){this.Tg=new PBa(this);this.Tg.lr=null;this.Tg.l=this.B;this.Tg.connect(a)};
g.h.uy=function(){return 0==this.g};
g.h.mC=function(a){this.Vg=null;aCa(this,a)};
g.h.lC=function(){this.kg=null;this.wc=new L6(this,this.o,"rpc",this.D);this.wc.fi=null;this.wc.qr=0;var a=this.Iw.clone();g.Om(a,"RID","rpc");g.Om(a,"SID",this.o);g.Om(a,"CI",this.Ap?"0":"1");g.Om(a,"AID",this.Jj);a7(this,a);if(!g.yd||g.tc(10))g.Om(a,"TYPE","xmlhttp"),M6(this.wc,a,!0,this.Ln,!1);else{g.Om(a,"TYPE","html");var b=this.wc,c=!!this.Ln;b.vj=3;b.eh=n6(a.clone());LBa(b,c)}};
g.h.hC=function(a,b){if(0!=this.g&&(this.wc==a||this.Rd==a))if(this.If=a.Yk,this.Rd==a&&3==this.g)if(7<this.Rh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.kg){if(this.wc)if(this.wc.bk+3E3<this.Rd.bk)c7(this),this.wc.cancel(),this.wc=null;else break a;e7(this);P6(19)}}else this.wz=c[1],0<this.wz-this.Jj&&37500>c[2]&&this.Ap&&0==this.Wi&&!this.Th&&(this.Th=U6((0,g.z)(this.uP,this),6E3));else f7(this,11)}else b!=wDa.ZX.g&&f7(this,11);else if(this.wc==a&&
c7(this),!g.C(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Jj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Ln=e[2],e=e[3],null!=e?this.Rh=e:this.Rh=6,this.g=3,this.qd&&this.qd.Tw(),this.Iw=X6(this,this.Tl()?this.Ln:null,this.kr),bCa(this)):"stop"==e[0]&&f7(this,7):3==this.g&&("stop"==e[0]?f7(this,7):"noop"!=e[0]&&this.qd&&this.qd.Sw(e),this.Wi=0)}}};
g.h.uP=function(){null!=this.Th&&(this.Th=null,this.wc.cancel(),this.wc=null,e7(this),P6(20))};
g.h.Co=function(a){if(this.wc==a){c7(this);this.wc=null;var b=2}else if(this.Rd==a)this.Rd=null,b=1;else return;this.If=a.Yk;if(0!=this.g)if(a.uf)1==b?(b=(0,g.F)()-a.bk,g7.dispatchEvent(new TBa(g7,a.Ei?a.Ei.length:0,b,this.jj)),b7(this),this.A.length=0):bCa(this);else{var c=a.fh,d;if(!(d=3==c||7==c||0==c&&0<this.If)){if(d=1==b)this.Rd||this.Vg||1==this.g||2<=this.jj?d=!1:(this.Vg=U6((0,g.z)(this.mC,this,a),cCa(this,this.jj)),this.jj++,d=!0);d=!(d||2==b&&e7(this))}if(d)switch(c){case 1:f7(this,5);
break;case 4:f7(this,10);break;case 3:f7(this,6);break;case 7:f7(this,12);break;default:f7(this,2)}}};
g.h.pI=function(a){if(!g.Qa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.PU=function(a){a?P6(2):(P6(1),dCa(this,8))};
g.h.Hq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.lx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.nf=function(a){g7.dispatchEvent(new UBa(g7,a))};
g.h.Tl=function(){return!(!g.yd||g.tc(10))};
g.h=eCa.prototype;g.h.Tw=function(){};
g.h.Sw=function(){};
g.h.Rw=function(){};
g.h.uq=function(){};
g.h.Xx=function(){return{}};
g.h.isActive=function(){return!0};g.A(h7,g.K);g.h=h7.prototype;g.h.SS=function(){this.dd=Math.min(3E5,2*this.dd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.dd+15E3*Math.random();g.gu(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.dd=5E3};g.A(i7,eCa);g.h=i7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Id=function(a){return this.o.Id(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.cf(this.o),hCa(this),g.cf(this.l),this.l=null)};
g.h.ia=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new $6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Jj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):j7(this)&&ZBa(this.g,c)};
g.h.Tw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)ZBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Rw=function(a){var b=2==a&&401==this.g.If;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.uq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Xx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.gc(a,this.B);return a};
g.h.Sw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),XBa(this.g)):this.R("handlerMessage",new fCa(a[0],a[1]))};
g.h.yV=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Rd&&b++;0!=b||this.connect(this.B,this.A)};k7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
k7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
k7.prototype.B=function(a){a(Error("request timed out"))};var pCa=(0,g.F)(),n7=null,q7=Array(50),p7=-1,r7=!1;g.A(s7,g.UF);s7.prototype.ke=function(){return this.g};
s7.prototype.contains=function(a){return!!v6(this.g,a)};
s7.prototype.get=function(a){return a?w6(this.g,a):null};
s7.prototype.info=function(a){o7(this.D,a)};g.A(t7,g.UF);var xDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=t7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.uE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.eE(this.xa),this.xa=window.NaN)};
g.h.V=function(){this.stop();t7.Z.V.call(this)};
g.h.uE=function(){this.xa=window.NaN;this.g=g.AE(l7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.AV,this),onError:(0,g.z)(this.zV,this),wd:(0,g.z)(this.BV,this)})};
g.h.AV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new q6(c))};
g.h.zV=function(a){this.g=null;a.status&&404==a.status?this.l>=xDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=xDa[this.l],this.xa=g.cE((0,g.z)(this.uE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.BV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(v7,s7);g.h=v7.prototype;g.h.start=function(){u7(this)&&this.R("screenChange");!g.aH("yt-remote-lounge-token-expiration")&&tCa(this);g.eE(this.l);this.l=g.cE((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){u7(this);qCa(this,a);w7(this,!1);this.R("screenChange");b(a);a.token||tCa(this)};
g.h.remove=function(a,b){var c=u7(this);sCa(this,a)&&(w7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.wp=function(a,b,c,d){var e=u7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,w7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.eE(this.l);v7.Z.V.call(this)};
g.h.XI=function(a){u7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}w7(this,!b);b&&o7(this.D,"Missed "+b+" lounge tokens.")};
g.h.WI=function(a){o7(this.D,"Requesting lounge tokens failed: "+a)};g.A(y7,g.UF);g.h=y7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.aH("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?A7(this):(this.A=(0,g.F)()+3E5,g.$G("yt-remote-fast-check-period",this.A),this.nu())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){x7("Updating availability on schedule.");var a=this.C(),b=g.Nb(this.g,function(b,d){return b&&!!w6(a,d)},this);
z7(this,b)};
g.h.V=function(){g.eE(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);y7.Z.V.call(this)};
g.h.nu=function(){g.eE(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=wCa(this);if(g.Qb(a)){var b=l7(this.B,"/pairing/get_screen_availability");this.l=m7(this.B,b,{lounge_token:g.Tb(a).join(",")},(0,g.z)(this.AS,this,a),(0,g.z)(this.zS,this))}else z7(this,{}),A7(this)};
g.h.AS=function(a,b){this.l=null;var c=g.Tb(wCa(this));if(g.kb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;z7(this,d);A7(this)}else this.gc("Changing Screen set during request."),this.nu()};
g.h.zS=function(a){this.gc("Screen availability failed: "+a);this.l=null;A7(this)};
g.h.gc=function(a){o7("OnlineScreenService",a)};g.A(B7,s7);g.h=B7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.wp=function(a,b,c,d){this.o.contains(a)?this.o.wp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,o7(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Ya(this.g,(0,g.Ld)(this.A,function(a){return!this.contains(a)},this))};
g.h.vE=function(){return(0,g.Ld)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.wE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new t7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.cf(f);d(C7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.cf(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.EV=function(a,b,c,d){g.AE(l7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new q6(d.screen||{});if(!e.name||ACa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);ACa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(C7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.cf(this.o);g.cf(this.l);B7.Z.V.call(this)};
g.h.mJ=function(){BCa(this);this.R("screenChange");this.l.update()};
B7.prototype.dispose=B7.prototype.dispose;g.A(E7,g.UF);g.h=E7.prototype;g.h.Do=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.se=function(a){this.ia()||(a&&F7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){o7(this.M,a)};
g.h.yE=function(){return null};
g.h.xu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){F7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.xu("");E7.Z.V.call(this)};g.A(G7,E7);g.h=G7.prototype;g.h.wu=function(a){if(this.g){if(this.g==a)return;F7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);DCa(this)};
g.h.Kj=function(a){this.info("launchWithParams no-op for Cast: "+g.Bg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.se()},this),(0,g.z)(function(){this.se(Error("Failed to stop receiver app."))},this)):this.se(Error("Stopping cast device witout session."))};
g.h.xu=g.y;g.h.V=function(){this.info("disposeInternal");g.eE(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;G7.Z.V.call(this)};
g.h.ET=function(a,b){if(!this.ia())if(b){var c=g.fx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bg(c));switch(d){case "mdxSessionStatus":CCa(this,c.screenId);break;default:F7(this,"Unknown youtube message: "+d)}}else F7(this,"Unable to parse message.")}else F7(this,"No data in message.")};
g.h.ky=function(a,b,c,d){zCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(F7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.cE((0,g.z)(this.ky,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.yE=function(){return this.g};
g.h.FV=function(a){this.ia()||a||(F7(this,"Cast session died."),this.se())};g.A(H7,E7);g.h=H7.prototype;g.h.wu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Kj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.eE(this.C);this.A?this.A.stop((0,g.z)(this.se,this,null),(0,g.z)(this.se,this,"Failed to stop DIAL device.")):this.se()};
g.h.V=function(){this.g();this.g=g.y;g.eE(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;H7.Z.V.call(this)};
g.h.IV=function(a){this.ia()||a||(F7(this,"DIAL session died."),this.g(),this.g=g.y,this.se())};
g.h.Yr=function(a){this.I=u6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,FCa(this));a(b);ECa(this)}else this.D=(0,g.z)(function(){g.eE(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,FCa(this));a(b);ECa(this)},this),this.C=g.cE((0,g.z)(function(){this.D()},this),100)};
g.h.AK=function(a,b,c){zCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Do(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Yr(b,c)},this),(0,g.z)(function(a){F7(this,"Failed to get DIAL screen: "+a);
this.Yr(b,c)},this))};g.A(I7,E7);I7.prototype.stop=function(){this.se()};
I7.prototype.wu=g.y;I7.prototype.Kj=function(){g.eE(this.g);this.g=window.NaN;var a=w6(this.H.ke(),this.l.label);a?this.Do(a):this.se(Error("No such screen"))};
I7.prototype.V=function(){g.eE(this.g);this.g=window.NaN;I7.Z.V.call(this)};g.A(J7,g.UF);g.h=J7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.iC,this),(0,g.z)(this.kS,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.fQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.A),mCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.xE,this)),this.o=HCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.Bg(a))},this)),this.R("yt-remote-cast2-availability-change",L7(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.Bg(a));
b(!1)},this))};
g.h.zU=function(a,b){K7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)K7("Unsetting old screen status: "+this.g.l.friendlyName),M7(this,null)}if(a&&b){if(!this.g){c=w6(this.l.ke(),a);if(!c){K7("setConnectedScreenStatus: Unknown screen.");return}var d=GCa(this,c);d||(K7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.Bg(a))},this)));
K7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);M7(this,new I7(this.l,d),!0)}this.g.xu(b)}else K7("setConnectedScreenStatus: no screen.")};
g.h.AU=function(a){this.ia()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Kj(a):this.gc("Setting connection data without a session")};
g.h.HV=function(){this.ia()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),M7(this,null)):K7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.iC,this),(0,g.z)(this.FS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.xE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Va(g.x("yt.mdx.remote.debug.handlers_")||[],jCa);g.cf(this.g);J7.Z.V.call(this)};
g.h.gc=function(a){o7("Controller",a)};
g.h.jC=function(a,b){this.g==a&&(b||M7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.gS=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),K7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)K7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{K7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:M7(this,
new I7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:M7(this,new H7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:M7(this,new G7(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.fQ=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return K7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);M7(this,new H7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.AK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Yr,b))};
g.h.iC=function(a){if(!this.ia()){K7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)K7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),M7(this,new G7(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=w6(this.l.ke(),c.label);
d&&r6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(K7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.cf(this.g),this.g=new G7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.jC,this,this.g)),this.g.Kj(null));this.g.wu(a)}}};
g.h.GV=function(){return this.g?this.g.yE():null};
g.h.FS=function(a){this.ia()||(this.gc("Failed to estabilish a session: "+g.Bg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&M7(this,null))};
g.h.kS=function(a){K7("Receiver availability updated: "+a);if(!this.ia()){var b=L7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;L7(this)!=b&&this.R("yt-remote-cast2-availability-change",L7(this))}};
g.h.xE=function(){this.ia()||(this.o=HCa(this),K7("Updating custom receivers: "+g.Bg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",L7(this)))};
J7.prototype.setLaunchParams=J7.prototype.AU;J7.prototype.setConnectedScreenStatus=J7.prototype.zU;J7.prototype.stopSession=J7.prototype.HV;J7.prototype.getCastSession=J7.prototype.GV;J7.prototype.requestSession=J7.prototype.requestSession;J7.prototype.init=J7.prototype.init;J7.prototype.dispose=J7.prototype.dispose;var S7=[];g.h=X7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";Y7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+Z7(this):this.H};
g.h.clone=function(){return new X7(c8(this))};g.A(e8,g.UF);g.h=e8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,k8(this,"play")):j8(this,"play"),i8(this,1,a8(f8(this))),this.R("remotePlayerChange")):g8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,k8(this,"pause")):j8(this,"pause"),i8(this,2,a8(f8(this))),this.R("remotePlayerChange")):g8(this,this.pause)};
g.h.tE=function(a){if(1==this.g){if(this.l){var b=f8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,k8(this,"seekTo",{newTime:a}))}else j8(this,"seekTo",{newTime:a});i8(this,3,a);this.R("remotePlayerChange")}else g8(this,g.Fa(this.tE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,k8(this,"stopVideo")):j8(this,"stopVideo");var a=f8(this);a.index=-1;a.videoId="";Y7(a);h8(this,a);this.R("remotePlayerChange")}else g8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=f8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){o7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){o7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);j8(this,"setVolume",e)}c.muted=b;c.volume=a;h8(this,c)}else g8(this,g.Fa(this.setVolume,a,b))};
g.h.vD=function(a,b){if(1==this.g){var c=f8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Bg(b.style),g.gc(d,c.l));j8(this,"setSubtitlesTrack",d);h8(this,c)}else g8(this,g.Fa(this.vD,a,b))};
g.h.hv=function(a,b){if(1==this.g){j8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=f8(this);c.audioTrackId=b.Pb.id;h8(this,c)}else g8(this,g.Fa(this.hv,a,b))};
g.h.sE=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);b8(c,a,b);h8(this,c)}j8(this,"previous")}else g8(this,g.Fa(this.sE,a,b))};
g.h.rE=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);b8(c,a,b);h8(this,c)}j8(this,"next")}else g8(this,g.Fa(this.rE,a,b))};
g.h.Cx=function(){1==this.g?j8(this,"dismissAutoplay"):g8(this,this.Cx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}e8.Z.dispose.call(this)};
g.h.V=function(){UCa(this);this.A=null;this.B.clear();d8(this,null);e8.Z.V.call(this)};
g.h.jv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.wC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.bS=function(a,b){this.R(a,b)};
g.h.BP=function(a){if(!a)this.Il(null),d8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=f8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)o7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,h8(this,b)}};
g.h.Il=function(a){o7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),VCa(this),this.R("remotePlayerChange")};
g.h.AP=function(a){a?(VCa(this),this.R("remotePlayerChange")):this.Il(null)};
g.h.OP=function(){var a=RCa();a&&d8(this,a)};
g.h.gc=function(a){o7("CP",a)};g.A(l8,g.UF);g.h=l8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;$7(this.Za,m);this.A="UNSUPPORTED";m8("Connecting with setPlaylist and params: "+g.Bg(l));this.g.connect({method:"setPlaylist",params:g.Bg(l)},a,qBa())}else m8("Connecting without params"),
this.g.connect({},a,qBa());XCa(this)};
g.h.dispose=function(){this.ia()||(this.R("beforeDispose"),n8(this,3));l8.Z.dispose.call(this)};
g.h.V=function(){o8(this);q8(this);p8(this);g.eE(this.H);this.H=window.NaN;g.eE(this.I);this.I=window.NaN;this.o=null;g.FF(this.P);this.P.length=0;this.g.dispose();l8.Z.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.MI=function(){this.C(2)};
g.h.FP=function(){m8("Channel opened");this.N&&(this.N=!1,p8(this),this.M=g.cE((0,g.z)(function(){m8("Timing out waiting for a screen.");this.C(1)},this),15E3));
uBa(gCa(this.g),this.X)};
g.h.CP=function(){m8("Channel closed");(0,window.isNaN)(this.B)?B6(!0):B6();this.dispose()};
g.h.DP=function(a){B6();(0,window.isNaN)(this.F())?(m8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,m8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),n8(this,2))};
g.h.EP=function(a){a.params?m8("Received: action="+a.action+", params="+g.Bg(a.params)):m8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.fx(a.params.devices);this.l=(0,g.G)(a,function(a){return new p6(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
$Ca(this,a);break;case "loungeScreenDisconnected":g.Wa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
$Ca(this,!1);break;case "remoteConnected":var b=new p6(g.fx(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Ta(this.l,b);
break;case "remoteDisconnected":b=new p6(g.fx(a.params.device));g.Wa(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":bDa(this,a);break;case "nowPlaying":dDa(this,a);break;case "onStateChange":cDa(this,a);break;case "onAdStateChange":eDa(this,a);break;case "onVolumeChanged":fDa(this,a);break;case "onSubtitlesTrackChanged":aDa(this,a);break;case "nowAutoplaying":gDa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":hDa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:m8("Unrecognized action: "+a.action)}};
g.h.kU=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&r8(this,"getNowPlaying")}};
l8.prototype.subscribe=l8.prototype.subscribe;l8.prototype.unsubscribeByKey=l8.prototype.Id;l8.prototype.fa=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.F())?j7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
l8.prototype.getProxyState=l8.prototype.fa;l8.prototype.C=function(a){m8("Disconnecting with "+a);o8(this);this.R("beforeDisconnect",a);1==a&&B6();hCa(this.g,a);this.dispose()};
l8.prototype.disconnect=l8.prototype.C;l8.prototype.da=function(){var a=this.Za;this.o&&(a=this.Za.clone(),b8(a,this.o,a.index));return c8(a)};
l8.prototype.getPlayerContextData=l8.prototype.da;
l8.prototype.na=function(a){var b=new X7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.eE(this.H),this.H=g.cE((0,g.z)(this.kU,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&a8(this.Za)==a8(b)&&g.Bg(this.Za.l)==g.Bg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
l8.prototype.setPlayerContextData=l8.prototype.na;l8.prototype.W=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
l8.prototype.getOtherConnectedRemoteId=l8.prototype.W;l8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
l8.prototype.getReconnectTimeout=l8.prototype.F;l8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
l8.prototype.getAutoplayMode=l8.prototype.Y;l8.prototype.ba=function(){return this.D||""};
l8.prototype.getAutoplayVideoId=l8.prototype.ba;l8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.hu(a.g);a.start()}};
l8.prototype.reconnect=l8.prototype.ra;l8.prototype.ha=function(a,b){r8(this,a,b);ZCa(this)};
l8.prototype.sendMessage=l8.prototype.ha;g.A(s8,s7);g.h=s8.prototype;g.h.ke=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.add=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.wp=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.cd.$_ubk(this.l[a]);this.l.length=0;this.cd=null;s8.Z.V.call(this)};
g.h.CV=function(){this.R("screenChange")};
g.h.CR=function(){this.R("onlineScreenChange")};
B7.prototype.$_st=B7.prototype.start;B7.prototype.$_gspc=B7.prototype.EV;B7.prototype.$_gsppc=B7.prototype.wE;B7.prototype.$_c=B7.prototype.contains;B7.prototype.$_g=B7.prototype.get;B7.prototype.$_a=B7.prototype.add;B7.prototype.$_un=B7.prototype.wp;B7.prototype.$_r=B7.prototype.remove;B7.prototype.$_gs=B7.prototype.ke;B7.prototype.$_gos=B7.prototype.vE;B7.prototype.$_s=B7.prototype.subscribe;B7.prototype.$_ubk=B7.prototype.Id;var t8=null,u8=null,J8=null,y8=[];g.p(K8,g.K);g.h=K8.prototype;
g.h.V=function(){g.K.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.gC,this);this.g.unsubscribe("remotePlayerChange",this.Ll,this);this.g.unsubscribe("remoteQueueChange",this.Eo,this);this.g.unsubscribe("autoplayUpNext",this.DB,this);this.g.unsubscribe("previousNextChange",this.dC,this);this.g.unsubscribe("nowAutoplaying",this.VB,this);this.g.unsubscribe("autoplayDismissed",this.CB,this);this.g=this.F=null};
g.h.FA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(N8(this)){if(!f8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":f8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.tj(c[0],c[1]);break;case "control_subtitles_set_track":O8(this,c[0]);break;case "control_set_audio_track":c=c[0],N8(this)&&this.g.hv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();P8(this,0==c?void 0:c);break;case "control_seek":P8(this,c[0]);break;case "control_subtitles_set_track":O8(this,c[0]);break;case "control_set_audio_track":c=c[0],N8(this)&&this.g.hv(this.l.ea(1).videoId,c)}};
g.h.zP=function(a){this.K.HI(a)};
g.h.fV=function(a){this.FA("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.ID=function(){var a=this.l.zc("captions","track");g.Zb(a)||O8(this,a)};
g.h.TB=function(a){if(N8(this)){this.g.unsubscribe("remotePlayerChange",this.Ll,this);var b=Math.round(a.volume);a=!!a.muted;var c=f8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Ll,this)}};
g.h.UQ=function(){g.Zb(this.C)||tDa(this,this.C);this.D=!1};
g.h.gC=function(a,b){this.B.stop();2==b&&this.FD()};
g.h.Ll=function(){if(N8(this)){this.A.stop();var a=f8(this.g);switch(a.g){case 1081:case 1:M8(this,new g.sP(8));this.ED();break;case 1085:case 3:M8(this,new g.sP(9));break;case 1083:case 0:M8(this,new g.sP(2));this.I.stop();L8(this,this.l.ea().lengthSeconds);break;case 1084:M8(this,new g.sP(4));break;case 2:M8(this,new g.sP(4));L8(this,a8(a));break;case -1:M8(this,new g.sP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},M8(this,new g.sP(128,a))}a=f8(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,tDa(this,a));a=f8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.gE()}else sDa(this)};
g.h.dC=function(){this.l.R("mdxpreviousnextchange")};
g.h.Eo=function(){N8(this)||sDa(this)};
g.h.UH=function(){this.g.Cx()};
g.h.DB=function(a){a&&(a=g.AE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.fT,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.fT=function(a,b){var c=new g.eO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.VB=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.CB=function(){this.l.R("mdxautoplaycanceled")};
g.h.EN=function(a,b){-1==f8(this.g).g?P8(this,a):b&&this.g.tE(a)};
g.h.gE=function(){if(N8(this)){var a=f8(this.g);this.o.Ba(this.P);a.muted?this.l.mute():this.l.Wf();this.l.setVolume(a.volume);this.P=this.o.O(this.l,"onVolumeChange",this.TB)}};
g.h.ED=function(){this.A.stop();if(!this.g.ia()){var a=f8(this.g);a.kb()&&M8(this,new g.sP(8));L8(this,a8(a));this.A.start()}};
g.h.FD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(Q8,g.U);Q8.prototype.A=function(a){vDa(this,a.state)};g.p(R8,g.OZ);R8.prototype.I=function(){var a=this.l.zc("remote","receivers");a&&1<a.length&&!this.l.zc("remote","quickCast")?(this.F=g.nb(a,this.B,this),g.PZ(this,(0,g.G)(a,this.B)),a=this.l.zc("remote","currentReceiver"),this.mf(this.B(a)),this.enable(!0)):this.enable(!1)};
R8.prototype.B=function(a){return a.key};
R8.prototype.lf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
R8.prototype.td=function(a){g.OZ.prototype.td.call(this,a);this.l.Gd("remote","currentReceiver",this.F[a]);this.A.Qb()};g.p(S8,g.rV);g.h=S8.prototype;g.h.create=function(){mDa(g.wM(g.X(this.g)));this.C.push(g.fG("yt-remote-before-disconnect",this.vP,this));this.C.push(g.fG("yt-remote-connection-change",this.lS,this));this.C.push(g.fG("yt-remote-receiver-availability-change",this.eC,this));this.C.push(g.fG("yt-remote-auto-connect",this.jS,this));this.C.push(g.fG("yt-remote-receiver-resumed",this.iS,this));this.eC()};
g.h.load=function(){this.g.Ys();g.rV.prototype.load.call(this);this.B=new K8(this,this.g,this.l);var a=(a=rDa())?a.currentTime:0;var b=I8()?new e8(D8(),void 0):null;0==a&&b&&(a=a8(f8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));uDa(this,this.D,this.D);g.$_(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.df(this.B,this.l);this.l=this.B=null;g.rV.prototype.unload.call(this);g.$_(this.g.app,5)};
g.h.V=function(){g.gG(this.C);g.rV.prototype.V.call(this)};
g.h.Al=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.FA.apply(this.B,[a].concat(g.pa(c)))};
g.h.DI=function(){return this.loaded?this.B.suggestion:null};
g.h.Lf=function(){return this.l?f8(this.l).Lf:!1};
g.h.hasNext=function(){return this.l?f8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.sN=function(){var a=f8(this.l),b=this.g.ea();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+Z7(a):a.A,isPeggedToLive:1>=(a.C?a.o+Z7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+Z7(a):a.o,seekableStart:0<a.B?a.B+Z7(a):a.B}};
g.h.tN=function(){this.l&&this.l.rE()};
g.h.uN=function(){this.l&&this.l.sE()};
g.h.vP=function(a){1==a&&(this.I=this.l?f8(this.l):null)};
g.h.lS=function(){var a=I8()?new e8(D8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.cf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.gA(a.videoId,a8(a)));this.g.R("videodatachange","newdata",this.g.ea(),3)};
g.h.eC=function(){this.F=[this.o].concat(oDa());var a=E8()||this.o;T8(this,a);this.g.ua("onMdxReceiversChange")};
g.h.jS=function(){var a=E8();T8(this,a)};
g.h.iS=function(){this.A=E8()};
g.h.rN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?V7():T8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&V7(),!0):!1}};
g.h.vN=function(){j8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Oc=function(){return!1};g.fY.remote=S8;})(_yt_player);
